// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_RETURN-0]
	_ = x[OP_CONST-1]
	_ = x[OP_NEGATE-2]
	_ = x[OP_ADD-3]
	_ = x[OP_SUBTRACT-4]
	_ = x[OP_MULTIPLY-5]
	_ = x[OP_DIVIDE-6]
	_ = x[OP_CONST_LONG-7]
}

const _OpCode_name = "OP_RETURNOP_CONSTOP_NEGATEOP_ADDOP_SUBTRACTOP_MULTIPLYOP_DIVIDEOP_CONST_LONG"

var _OpCode_index = [...]uint8{0, 9, 17, 26, 32, 43, 54, 63, 76}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
