package compiler_test

import (
	"testing"

	"go-bytecode-interpreter/internals/compiler"
)

// TestOpCode_String requires internals/compiler/opcode_string.go to exist,
// generated by `go generate ./internals/compiler` (opcodes.go's
// //go:generate stringer directive). It replaces the previous hand-written
// String() method removed in this commit. Until that file is generated,
// this test fails to compile — see the human-facing note on the
// //go:generate directive's typo ("OpCOde" vs "OpCode").
func TestOpCode_String(t *testing.T) {
	cases := []struct {
		op   compiler.OpCode
		want string
	}{
		{compiler.OP_RETURN, "OP_RETURN"},
		{compiler.OP_CONST, "OP_CONST"},
		{compiler.OP_NEGATE, "OP_NEGATE"},
		{compiler.OP_ADD, "OP_ADD"},
		{compiler.OP_SUBTRACT, "OP_SUBTRACT"},
		{compiler.OP_MULTIPLY, "OP_MULTIPLY"},
		{compiler.OP_DIVIDE, "OP_DIVIDE"},
		{compiler.OP_CONST_LONG, "OP_CONST_LONG"},
	}

	for _, tc := range cases {
		t.Run(tc.want, func(t *testing.T) {
			if got := tc.op.String(); got != tc.want {
				t.Errorf("String() = %q, want %q", got, tc.want)
			}
		})
	}
}

// TestOpCode_String_OutOfRange asserts an OpCode value past the last
// defined constant still stringifies without panicking. The hand-written
// String() this replaces had an explicit "UNKNOW OP_CODE" default case;
// stringer's generated fallback format is different
// ("OpCode(9)") — this test only pins down that it doesn't panic, not the
// exact fallback string, since that's generated code the human doesn't
// author by hand.
func TestOpCode_String_OutOfRange(t *testing.T) {
	invalid := compiler.OpCode(255)
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("String() panicked on out-of-range OpCode: %v", r)
		}
	}()
	_ = invalid.String()
}
